[package]
name = "health_check"
version = "0.1.0"
authors = ["Paul Stey <paulstey@gmail>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3.2"
